### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by IgorStolbov** [Evfro/polara#1]
The code is not compatible with Python 3. The usage of "Print" function is obsolete.

**Comment by Evfro** [comment]
There are potentially more issues with Python 3 compatibility than just print function. However, even though the project started on Python 2 due to some compatibility concerns, they are most probably gone now and migration to Python 3 is in plans. However, full transition requires considerable efforts including thorough testing and will take quite some time. Suggestions on how to make this transition as painless as possible are welcome.

There's also a different task of substituting print function with adequate logger, which is an important task as well and will be resolved much sooner. But it's unlikely to resolve 2 vs. 3 compatibility problem.

**Comment by Evfro** [comment]
Closing. Fixed by [0.5.1 release](https://github.com/Evfro/polara/releases/tag/v0.5.1).
